from importlib.metadata import distribution
import os
import random
import re
import sys
from unittest import result

DAMPING = 0.85
SAMPLES = 10000


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: python pagerank.py corpus")
    corpus = crawl(sys.argv[1])
    ranks = sample_pagerank(corpus, DAMPING, SAMPLES)
    print(f"PageRank Results from Sampling (n = {SAMPLES})")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")
    ranks = iterate_pagerank(corpus, DAMPING)
    print(f"PageRank Results from Iteration")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")


def crawl(directory):
    """
    Parse a directory of HTML pages and check for links to other pages.
    Return a dictionary where each key is a page, and values are
    a list of all other pages in the corpus that are linked to by the page.
    """
    pages = dict()

    # Extract all links from HTML files
    for filename in os.listdir(directory):
        if not filename.endswith(".html"):
            continue
        with open(os.path.join(directory, filename)) as f:
            contents = f.read()
            links = re.findall(r"<a\s+(?:[^>]*?)href=\"([^\"]*)\"", contents)
            pages[filename] = set(links) - {filename}

    # Only include links to other pages in the corpus
    for filename in pages:
        pages[filename] = set(
            link for link in pages[filename]
            if link in pages
        )

    return pages


def transition_model(corpus, page, damping_factor):
    """
    Return a probability distribution over which page to visit next,
    given a current page.

    With probability `damping_factor`, choose a link at random
    linked to by `page`. With probability `1 - damping_factor`, choose
    a link at random chosen from all pages in the corpus.
    """
    dist = {}
    links = corpus[page]

    # If page has no outgoing links, then function should return a probability distribution that chooses randomly among all pages with equal probability. 
    if len(links) == 0:
        for link in corpus:
            dist[link] = 1 / len(corpus)
    else:
        # With probability damping_factor, the random surfer should randomly choose one of the links from page with equal probability.
        # With probability 1 - damping_factor, the random surfer should randomly choose one of all pages in the corpus with equal probability.
        for link in corpus:
            dist[link] = (1 - damping_factor) / len(corpus)
        for link in links:
            dist[link] += damping_factor / len(links)
    
    return dist


def sample_pagerank(corpus, damping_factor, n):
    """
    Return PageRank values for each page by sampling `n` pages
    according to transition model, starting with a page at random.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """

    page_rank = {}
    for key in corpus.keys():
        page_rank[key] = 0
    # The first sample should be generated by choosing from a page at random.
    sample_page = random.choice(list(corpus.keys()))
    # For each of the remaining samples, the next sample should be generated from the previous sample based on the previous sample’s transition model.
    for i in range(1, n):
        page_rank[sample_page] += 1
        page_dist = transition_model(corpus, sample_page, damping_factor)
        sample_page = random.choices(population = list(page_dist), weights= page_dist.values(), k=1)[0]

    for key in page_rank.keys():
        page_rank[key] /= n

    return page_rank


def iterate_pagerank(corpus, damping_factor):
    """
    Return PageRank values for each page by iteratively updating
    PageRank values until convergence.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    # PageRank formula = PR(p)
    # PR(p) = (1 - d) / N + d * Σ (PR(i) / NumLinks(i))
    N = len(corpus)
    D = damping_factor
    random_choice = (1 - D) / N
    page_rank = {}
    calculated_pr = {}
    condition = True
    # The function should begin by assigning each page a rank of 1 / N, where N is the total number of pages in the corpus.
    for page in corpus:
        page_rank[page] = 1 / N

    # The function should then repeatedly calculate new rank values based on all of the current rank values, according to the PageRank formula
    while condition:
        for current_page in page_rank:
            sum = 0.0
            for page in corpus:
                if current_page in corpus[page]:
                    NumLinks = len(corpus[page])
                    sum += page_rank[page] / NumLinks
                # A page that has no links at all should be interpreted as having one link for every page in the corpus (including itself)
                if not corpus[page]:
                    sum += page_rank[page] / N

            d_times_sum = D * sum
            calculated_pr[current_page] = random_choice + d_times_sum

        condition = False
        # This process should repeat until no PageRank value changes by more than 0.001 between the current rank values and the new rank values.
        for current_page in page_rank:
            if abs(page_rank[current_page] - calculated_pr[current_page]) > 0.001:
                condition = True
            page_rank[current_page] = calculated_pr[current_page]
    
    return page_rank

if __name__ == "__main__":
    main()
